apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
  namespace: marketplace
data:
  TENANT_ID: "2f61bfd8-630a-4b2e-a88f-e94a7bc89ee7"
  ADMIN_TENANT_ID: "b7917494-f3ad-4100-be45-cc735a893f85"
  AUTH_ENDPOINT: "http://marketplace-auth.marketplace.svc.cluster.local:8000/api/v1/auth"
  PRODUCT_MS_URL: "http://marketplace-product.marketplace.svc.cluster.local:8000/api/v1"
  TENANT_ENDPOINT: "http://marketplace-tenant.marketplace.svc.cluster.local:8000/api/tenant"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "postgres"
