apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-auth
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-auth
  template:
    metadata:
      labels:
        app: marketplace-auth
    spec:
      containers:
        - name: marketplace-auth
          image: marketplace-auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "marketplace-auth-db"
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: ADMIN_JWT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: JWT_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: DB_PASSWORD
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: ADMIN_TENANT_ID
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: TENANT_ID
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_NAME

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-tenant
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-tenant
  template:
    metadata:
      labels:
        app: marketplace-tenant
    spec:
      containers:
        - name: marketplace-tenant
          image: marketplace-tenant:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "marketplace-tenant-db"
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: ADMIN_JWT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: JWT_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: DB_PASSWORD
            - name: AUTH_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: AUTH_ENDPOINT
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: ADMIN_TENANT_ID
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: TENANT_ID
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_NAME

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-product
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-product
  template:
    metadata:
      labels:
        app: marketplace-product
    spec:
      containers:
        - name: marketplace-product
          image: marketplace-product:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "marketplace-product-db"
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: ADMIN_JWT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: JWT_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: DB_PASSWORD
            - name: AUTH_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: AUTH_ENDPOINT
            - name: TENANT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: TENANT_ENDPOINT
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: ADMIN_TENANT_ID
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: TENANT_ID
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_NAME

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-order
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-order
  template:
    metadata:
      labels:
        app: marketplace-order
    spec:
      containers:
        - name: marketplace-order
          image: marketplace-order:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "marketplace-order-db"
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: ADMIN_JWT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: JWT_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: DB_PASSWORD
            - name: AUTH_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: AUTH_ENDPOINT
            - name: PRODUCT_MS_URL
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: PRODUCT_MS_URL
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: ADMIN_TENANT_ID
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: TENANT_ID
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_NAME

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-wishlist
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-wishlist
  template:
    metadata:
      labels:
        app: marketplace-wishlist
    spec:
      containers:
        - name: marketplace-wishlist
          image: marketplace-wishlist:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "marketplace-wishlist-db"
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: ADMIN_JWT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: JWT_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: DB_PASSWORD
            - name: AUTH_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: AUTH_ENDPOINT
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: ADMIN_TENANT_ID
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: TENANT_ID
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: marketplace-config
                  key: DB_NAME
